services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "5000:5000"

    env_file:
      - .env

    depends_on:
      mongodb:
        condition: service_healthy

    restart: unless-stopped

  mongodb:
    image: mongo:8

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_DATABASE: password_manager

    volumes:
      - mongodb_data:/data/db

    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped

volumes:
  mongodb_data:
